"""Pickup message lines for FF8 (Steam 2013). Generated by
tools/dump_kernel_text.py pickups; do not edit by hand.

PICKUP_LINES: (kind, id) -> the field-text lines the game shows when that
check is collected: (field id, message index, vanilla bytes hex). kind
"item" = game item id (magazines, Magical Lamp, Solomon Ring); kind "tm" =
Timber Maniacs issue bit. The client rewrites the line in the resident
message table of that field, within the vanilla byte length."""

PICKUP_LINES: dict[tuple[str, int], tuple[tuple[int, int, str], ...]] = {
    ('item', 163): (
        (908, 12, '566361636774636220a94b67706a205263767220486d6d70aa2e'),  # timania5: Received [Girl Next Door]!
    ),
    ('item', 167): (
        (481, 3, '566361636774636220a9576d6a6d6b6d6c2056676c65aa2e'),  # eein3: Received [Solomon Ring]!
        (482, 3, '566361636774636220a9576d6a6d6b6d6c2056676c65aa2e'),  # eein31: Received [Solomon Ring]!
        (483, 3, '566361636774636220a9576d6a6d6b6d6c2056676c65aa2e'),  # eein32: Received [Solomon Ring]!
    ),
    ('item', 168): (
        (162, 27, '566361636774636220a9515f6567615f6a20505f6b6eaa2e'),  # bggate_5: Received [Magical Lamp]!
        (251, 21, '566361636774636220a9515f6567615f6a20505f6b6eaa2e'),  # bgsido_2: Received [Magical Lamp]!
    ),
    ('item', 177): (
        (470, 17, '566361636774636220a95b635f6e6d6c7120516d6c72666a773c204a67707172204d71717363aa2e'),  # edlabo1: Received [Weapons Monthly, First Issue]!
    ),
    ('item', 179): (
        (245, 114, '566361636774636220a95b635f6e6d6c7120516d6c72666a773c20456e70676a204d71717363aa2e'),  # bgryo2_1: Received [Weapons Monthly, April Issue]!
        (246, 7, '566361636774636220a95b635f6e6d6c7120516d6c72666a773c20456e70676a204d71717363aa2e'),  # bgryo2_2: Received [Weapons Monthly, April Issue]!
    ),
    ('item', 180): (
        (764, 3, '566361636774636220a95b635f6e6d6c7120516d6c72666a773c20515f77204d71717363aa2e'),  # glwater3: Received [Weapons Monthly, May Issue]!
    ),
    ('item', 182): (
        (215, 3, '566361636774636220a95b635f6e6d6c7120516d6c72666a773c204e736a77204d71717363aa2e'),  # bgmon_2: Received [Weapons Monthly, July Issue]!
    ),
    ('item', 183): (
        (886, 45, '566361636774636220a95b635f6e6d6c7120516d6c72666a773c20457365737172204d71717363aa2e'),  # tggate1: Received [Weapons Monthly, August Issue]!
    ),
    ('item', 184): (
        (965, 8, '566361636774636220a9476d6b605f72204f676c6520212122aa2e'),  # gpbigin6: Received [Combat King 001]!
    ),
    ('item', 186): (
        (108, 39, '566361636774636220a9476d6b605f72204f676c6520212124aa2e'),  # bchtl_1: Received [Combat King 003]!
    ),
    ('item', 187): (
        (408, 8, '566361636774636220a9476d6b605f72204f676c6520212125aa2e'),  # eccway21: Received [Combat King 004]!
    ),
    ('item', 188): (
        (394, 1, '566361636774636220a9476d6b605f72204f676c6520212126aa2e'),  # ebroad6: Received [Combat King 005]!
        (395, 1, '566361636774636220a9476d6b605f72204f676c6520212126aa2e'),  # ebroad6a: Received [Combat King 005]!
    ),
    ('item', 189): (
        (264, 9, '566361636774636220a954637220545f6a7120205a6d6a3b22aa2e'),  # bvtr_2: Received [Pet Pals  Vol.1]!
    ),
    ('item', 190): (
        (895, 34, '566361636774636220a954637220545f6a71205a6d6a3b2023aa2e'),  # tiagit4: Received [Pet Pals Vol. 2]!
    ),
    ('item', 195): (
        (145, 61, '566361636774636220a9536161736a72204a5f6c204daa2e'),  # bgbook_1: Received [Occult Fan I]!
    ),
    ('item', 196): (
        (337, 25, '566361636774636220a9536161736a72204a5f6c204d4daa2e'),  # dopub_3: Received [Occult Fan II]!
    ),
    ('item', 197): (
        (613, 21, '566361636774636220a9536161736a72204a5f6c204d4d4daa2e'),  # fhfish1: Received [Occult Fan III]!
        (631, 6, '566361636774636220a9536161736a72204a5f6c204d4d4daa2e'),  # fhwater1: Received [Occult Fan III]!
    ),
    ('item', 198): (
        (533, 4, '566361636774636220a9536161736a72204a5f6c204d5aaa2e'),  # ephall2: Received [Occult Fan IV]!
    ),
    ('tm', 0): (
        (110, 1, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b09303b3b3b09303b3b3b09303b3b3b3b3b3b5d6d732064676c67716663622070635f62676c652067722e'),  # bchtr_1: Found an old issue of [Timber Maniacs]!
    ),
    ('tm', 1): (
        (104, 13, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # bcform_1: Found an old issue of [Timber Maniacs]!
    ),
    ('tm', 2): (
        (336, 14, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # dopub_2: Found an old issue of [Timber Maniacs]!
    ),
    ('tm', 3): (
        (319, 0, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # dohtr_1: Found an old issue of [Timber Maniacs]!
    ),
    ('tm', 4): (
        (904, 1, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # timania1: Found an old issue of [Timber Maniacs]!
    ),
    ('tm', 5): (
        (901, 2, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # tihtr1: Found an old issue of [Timber Maniacs]!
    ),
    ('tm', 6): (
        (737, 0, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # glhtr1: Found an old issue of [Timber Maniacs]!
        (738, 44, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # glhtr1a: Found an old issue of [Timber Maniacs]!
    ),
    ('tm', 7): (
        (617, 98, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # fhmin1: Found an old issue of [Timber Maniacs]!
    ),
    ('tm', 8): (
        (616, 39, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # fhhtr1: Found an old issue of [Timber Maniacs]!
    ),
    ('tm', 9): (
        (887, 11, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # tggrave1: Found an old issue of [Timber Maniacs]!
    ),
    ('tm', 11): (
        (939, 2, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # tmhtr1: Found an old issue of [Timber Maniacs]!
        (942, 29, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # tmmin1: Found an old issue of [Timber Maniacs]!
    ),
    ('tm', 12): (
        (502, 1, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b09303b3b3b09303b3b3b09303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # ehblan3: Found an old issue of [Timber Maniacs]!
    ),
    ('tm', 13): (
        (851, 25, '4a6d736c62205f6c206d6a62206771717363206d6420a958676b60637020515f6c675f6171aa2e0209303b3b3b2009303b3b3b2009303b3b3b2009303b3b3b3b3b3b205d6d732064676c67716663622070635f62676c652067722e'),  # secont1: Found an old issue of [Timber Maniacs]!
    ),
}
