"""Regenerate ff8/encounters.py from the game's own encounter table.

Reads scene.out (1024 encounter records of 128 bytes) out of the Steam
install's Data/lang-en/battle.fs archive and emits one flag byte per
encounter id plus the community name list, so the client can tell a random
encounter (flags 0) from a scripted or boss fight (flags set) without a
hand-kept list.

Usage (from the repo root):

    .venv\\Scripts\\python.exe tools\\gen_encounters.py [--game DIR] [--names encounterId.md]

--game defaults to the usual Steam library path; --names defaults to
downloading reference/encounterId.md from ff8-speedruns/ff8-memory.
"""

import argparse
import re
import struct
import sys
import urllib.request
from pathlib import Path

DEFAULT_GAME = Path(r"F:\SteamLibrary\steamapps\common\FINAL FANTASY VIII")
NAMES_URL = ("https://raw.githubusercontent.com/ff8-speedruns/ff8-memory/"
             "master/reference/encounterId.md")
OUT = Path(__file__).resolve().parent.parent / "ff8" / "encounters.py"
RECORD = 128
COUNT = 1024
FLAGS_OFFSET = 1        # byte 0 is the battle stage id


def lzs_decompress(buf: bytes) -> bytes:
    """FF8 .fs entries: u32 compressed size, then FF7-style LZSS."""
    n = struct.unpack_from("<I", buf, 0)[0]
    src = buf[4:4 + n]
    out = bytearray()
    i = 0
    while i < len(src):
        flags = src[i]
        i += 1
        for bit in range(8):
            if i >= len(src):
                break
            if flags & (1 << bit):
                out.append(src[i])
                i += 1
            else:
                lo, hi = src[i], src[i + 1]
                i += 2
                offset = lo | ((hi & 0xF0) << 4)
                length = (hi & 0x0F) + 3
                pos = (offset + 18) & 0xFFF
                start = len(out) - ((len(out) - pos) & 0xFFF)
                for k in range(length):
                    p = start + k
                    out.append(out[p] if 0 <= p < len(out) else 0)
    return bytes(out)


def read_scene_out(game: Path) -> bytes:
    base = game / "Data" / "lang-en" / "battle"
    names = (base.with_suffix(".fl")).read_bytes().decode("latin-1").splitlines()
    fi = base.with_suffix(".fi").read_bytes()
    idx = next(i for i, n in enumerate(names) if n.lower().endswith("scene.out"))
    size, offset, compressed = struct.unpack_from("<III", fi, idx * 12)
    with open(base.with_suffix(".fs"), "rb") as f:
        f.seek(offset)
        data = f.read(size)
    if compressed:
        data = lzs_decompress(data)
    if len(data) != RECORD * COUNT:
        sys.exit(f"scene.out: expected {RECORD * COUNT} bytes, got {len(data)}")
    return data


def read_names(source: str | None) -> dict[int, str]:
    if source:
        text = Path(source).read_text(encoding="utf-8")
    else:
        with urllib.request.urlopen(NAMES_URL, timeout=30) as resp:
            text = resp.read().decode("utf-8")
    names = {}
    for line in text.splitlines():
        m = re.match(r"\| (\d+) \| (.*?) \|", line)
        if m and m.group(2) != "?":
            names[int(m.group(1))] = m.group(2).strip()
    return names


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--game", type=Path, default=DEFAULT_GAME)
    ap.add_argument("--names", default=None, help="local encounterId.md")
    args = ap.parse_args(argv)

    scene = read_scene_out(args.game)
    flags = bytes(scene[i * RECORD + FLAGS_OFFSET] for i in range(COUNT))
    names = read_names(args.names)

    lines = [
        '"""Encounter table for FF8 (Steam 2013). Generated by',
        "tools/gen_encounters.py from the game's scene.out; do not edit by hand.",
        "",
        "ENCOUNTER_FLAGS[id] is byte 1 of the 128-byte scene.out record: the",
        "battle flags. Random encounters carry 0; every scripted or boss fight",
        "carries at least SCRIPTED (0x80) or CANT_ESCAPE (0x01). Bit names follow",
        "the community scene.out editors (Doomtrain / OpenVIII); the client only",
        "relies on zero-vs-nonzero. ENCOUNTER_NAMES comes from ff8-memory",
        'reference/encounterId.md (ids the reference marks "?" are omitted).',
        '"""',
        "",
        "ENCOUNTER_COUNT = 1024",
        "",
        "FLAG_CANT_ESCAPE = 0x01",
        "FLAG_NO_VICTORY_SEQUENCE = 0x02",
        "FLAG_SHOW_TIMER = 0x04",
        "FLAG_NO_EXP = 0x08",
        "FLAG_SKIP_EXP_SCREEN = 0x10",
        "FLAG_STRUCK_FIRST = 0x20",
        "FLAG_BACK_ATTACK = 0x40",
        "FLAG_SCRIPTED = 0x80",
        "",
        "ENCOUNTER_FLAGS: bytes = bytes.fromhex(",
    ]
    hexs = flags.hex()
    for i in range(0, len(hexs), 64):
        lines.append(f'    "{hexs[i:i + 64]}"')
    lines.append(")")
    lines.append("")
    lines.append("ENCOUNTER_NAMES: dict[int, str] = {")
    for i in sorted(names):
        lines.append(f"    {i}: {names[i]!r},")
    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}: {sum(1 for f in flags if f)} flagged encounters, "
          f"{len(names)} names")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
